# Generated by Django 3.1.2 on 2020-12-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaHari', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaPaket', models.CharField(max_length=30)),
                ('jam', models.CharField(max_length=20)),
                ('hari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.hari')),
            ],
        ),
    ]
